apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DB_HOST: "my-rds.xxxxxx.us-east-1.rds.amazonaws.com"
  DB_USER: "admin"
  DB_PASSWORD: "password123"
  DB_NAME: "realtimeapp"
  RABBITMQ_URL: "amqp://rabbitmq"
