apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-frontend
  namespace: country-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: country-frontend
  template:
    metadata:
      labels:
        app: country-frontend
    spec:
      containers:
        - name: frontend
          image: 338121/weather_frontend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
