apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-frontend
  namespace: simple-weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-frontend
  template:
    metadata:
      labels:
        app: weather-frontend
    spec:
      containers:
        - name: frontend
          image: 338121/front:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: weather-frontend-service
  namespace: simple-weather
spec:
  selector:
    app: weather-frontend
  ports:
    - port: 80
      targetPort: 80


