apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: country-app-ingress
  namespace: country-app
  annotations:
    kubernetes.io/ingress.className: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: www.codenimbustech.com   # change to your domain or omit for wildcard
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: country-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: country-backend
                port:
                  number: 5000
