apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-logs-pvc
  namespace: country-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: backend-logs-sc
  resources:
    requests:
      storage: 5Gi
